### ISSUE TITLE
ModuleNotFoundError: No module named 'scrapingbee'

### ISSUE THREAD

**Issue by tpmccallum** [openchatai/OpenCopilot#654]
**Describe the bug**

An error keeps appearing; not sure if it is the cause of data sources (URLs) not being indexed, but I assume it is the reason. 

**To Reproduce**

`make install`

Then paste a URL in as a new data source, wait for the pages to appear in the UI as indexed, but the pages do not appear.

`make logs`

```
nginx_1       | 172.22.0.1 - - [22/Feb/2024:22:23:15 +0000] "GET /backend/data_sources/b/209aa85c-effa-4114-a7a0-1708f3f3dd0c HTTP/1.1" 200 36 "http://localhost:8888/copilot/209aa85c-effa-4114-a7a0-1708f3f3dd0c/knowledge" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
workers_1     | Traceback (most recent call last):
workers_1     |   File "/usr/local/bin/celery", line 8, in <module>
workers_1     |     sys.exit(main())
workers_1     |   File "/usr/local/lib/python3.9/site-packages/celery/__main__.py", line 15, in main
workers_1     |     sys.exit(_main())
workers_1     |   File "/usr/local/lib/python3.9/site-packages/celery/bin/celery.py", line 236, in main
workers_1     |     return celery(auto_envvar_prefix="CELERY")
workers_1     |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
workers_1     |     return self.main(*args, **kwargs)
workers_1     |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1078, in main
workers_1     |     rv = self.invoke(ctx)
workers_1     |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
workers_1     |     return _process_result(sub_ctx.command.invoke(sub_ctx))
workers_1     |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
workers_1     |     return ctx.invoke(self.callback, **ctx.params)
workers_1     |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
workers_1     |     return __callback(*args, **kwargs)
workers_1     |   File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
workers_1     |     return f(get_current_context(), *args, **kwargs)
workers_1     |   File "/usr/local/lib/python3.9/site-packages/celery/bin/base.py", line 134, in caller
workers_1     |     return f(ctx, *args, **kwargs)
workers_1     |   File "/usr/local/lib/python3.9/site-packages/celery/bin/worker.py", line 348, in worker
workers_1     |     worker = app.Worker(
workers_1     |   File "/usr/local/lib/python3.9/site-packages/celery/worker/worker.py", line 93, in __init__
workers_1     |     self.app.loader.init_worker()
workers_1     |   File "/usr/local/lib/python3.9/site-packages/celery/loaders/base.py", line 110, in init_worker
workers_1     |     self.import_default_modules()
workers_1     |   File "/usr/local/lib/python3.9/site-packages/celery/loaders/base.py", line 105, in import_default_modules
workers_1     |     return [self.import_task_module(m) for m in self.default_modules]
workers_1     |   File "/usr/local/lib/python3.9/site-packages/celery/loaders/base.py", line 105, in <listcomp>
workers_1     |     return [self.import_task_module(m) for m in self.default_modules]
workers_1     |   File "/usr/local/lib/python3.9/site-packages/celery/loaders/base.py", line 85, in import_task_module
workers_1     |     return self.import_from_cwd(module)
workers_1     |   File "/usr/local/lib/python3.9/site-packages/celery/loaders/base.py", line 91, in import_from_cwd
workers_1     |     return import_from_cwd(
workers_1     |   File "/usr/local/lib/python3.9/site-packages/celery/utils/imports.py", line 104, in import_from_cwd
workers_1     |     return imp(module, package=package)
workers_1     |   File "/usr/local/lib/python3.9/site-packages/celery/loaders/base.py", line 88, in import_module
workers_1     |     return importlib.import_module(module, package=package)
workers_1     |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
workers_1     |     return _bootstrap._gcd_import(name[level:], package, level)
workers_1     |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
workers_1     |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
workers_1     |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
workers_1     |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
workers_1     |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
workers_1     |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
workers_1     |   File "/app/workers/tasks/__init__.py", line 3, in <module>
workers_1     |     from workers.tasks.web_crawl import web_crawl
workers_1     |   File "/app/workers/tasks/web_crawl.py", line 25, in <module>
workers_1     |     from workers.tasks.web_scraping_strategy import get_scraper
workers_1     |   File "/app/workers/tasks/web_scraping_strategy.py", line 2, in <module>
workers_1     |     from scrapingbee import ScrapingBeeClient
workers_1     | ModuleNotFoundError: No module named 'scrapingbee'

```

**Expected behavior**

Should just go ahead and index pages from the URL provided

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
- Ubuntu Linux

**Comment by tpmccallum** [comment]
This seems to be resolved after the a `git pull` and `make install`
Currently on https://github.com/openchatai/OpenCopilot/commit/d68383542d075edc495aa5b8d60756d3fca151a0
Working great.
